services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: aitaskuser
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: aitaskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aitaskdb
      SPRING_DATASOURCE_USERNAME: aitaskuser
      SPRING_DATASOURCE_PASSWORD: securepassword
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend

  ai-agent:
    build:
      context: ./ai-agent
    container_name: ai-agent
    ports:
      - "5001:5001"
    depends_on:
      - backend
      - ollama
    environment:
      OLLAMA_URL: http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
